<a href="https://colab.research.google.com/github/KhaledR/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Final Exam


In [11]:
import numpy as np
from numpy.linalg import eig

###Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)

In [23]:
equation1 = np.array([[1,1,1],[1,0,4],[0,0,5]])
equation2 = np.array([[89],[89],[95]])
amount = np.linalg.inv(equation1).dot(equation2)
print(amount)






[[13.]
 [57.]
 [19.]]


###Problem 2. Solve each system: (30 points)

In [21]:
a = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(a)



b = np.array([[5],[15],[-20]])
print(b)

inv_a = np.linalg.inv(a)

#AA^-1x = BA^-1
X = np.dot(inv_a,b)
print(X)

#It is not answerable because the cause of the error is that it is a singular matrix.
#The inverse property that was used in getting the solution is cannot be solved by 
#any method because of the error

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]


LinAlgError: ignored

###Problem 3. Consider the matrix, (40 points)

In [13]:
A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])

k,r = np.linalg.eig(A)
print("The eigenvalue/s is/are:",k)
print("The eigenvectors are:",r)

The eigenvalue/s is/are: [-1.  3.  2.]
The eigenvectors are: [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]
