<a href="https://colab.research.google.com/github/KhaledR/Linear-Algebra-58020/blob/main/Matrix_and_Its_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#Addition 

import numpy as np

a = np.array([[-5,0],[4,1]])
b = np.array([[6,-3],[2,3]])
print(a+b)

[[ 1 -3]
 [ 6  4]]


In [5]:
a = np.array([[-5,0],[4,1]])
b = np.array([[6,-3],[2,3]])
print(a-b)

[[-11   3]
 [  2  -2]]


In [6]:
b = np.array([[6,-3],[2,3]])
print(b-b)

[[0 0]
 [0 0]]
