<a href="https://colab.research.google.com/github/KhaledR/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Midterm Exam

In [2]:
import numpy as np

##Question 1

##Question 2

In [18]:
np.triu([[5,2,6],[8,3,1],[9,4,7]])


array([[5, 2, 6],
       [0, 3, 1],
       [0, 0, 7]])

##Question 3

##Question 4

In [3]:
C = np.array([[1,2,3],[2,3,3],[3,4,-2]])
inv_C = np.linalg.inv(C) #initiation of inverse
print(inv_C) #output

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


##Question 5

In [6]:
#Finding the Determinant

C = np.array([[1,2,3],[2,3,3],[3,4,-2]])
det_C = np.linalg.det(C) #initiation of determinant
print(det_C) #output


5.000000000000001


##Question 6

In [4]:
A = np.array([[5,4,1],[10,9,4],[10,13,15]])

inv_A = np.linalg.inv(A)

B = np.array([[3.4],[8.8],[19.2]])

X = np.dot(inv_A,B)
print(X) #output


[[0.2]
 [0.4]
 [0.8]]
