<a href="https://colab.research.google.com/github/KhaledR/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Practical Lab Exam 1

##Problem 1

###a. WY

In [27]:
import numpy as np

W = np.array([[1,-3],[2,-2],[3,1]])
Y = np.array([[1,2,0],[0,-1,2]])

result1 = np.dot(W,Y)
print(result1)


[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


###b. Z+Z

In [24]:
Z = np.array([[0,1],[2,3]])

result2 = np.add(Z,Z)
print(result2)


[[0 2]
 [4 6]]


###c. 3X

In [26]:
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])

result3 = np.dot(3,X)
print(result3)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


##Problem 2

###a. The product (YW)^2 is not defined

In [35]:
W = np.array([[1,-3],[2,-2],[3,1]])
Y = np.array([[1,2,0],[0,-1,2]])

dotresult = np.dot(Y,W)
result4 = np.square(dotresult)
print(result4) #False

[[25 49]
 [16 16]]


###b. WY - *X*

In [30]:
W = np.array([[1,-3],[2,-2],[3,1]])
Y = np.array([[1,2,0],[0,-1,2]])
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])

dotresult = np.dot(W,Y)
result5 = np.subtract(dotresult,X)
print(result5) #True


[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]


###c. YW - Z^2

In [36]:
W = np.array([[1,-3],[2,-2],[3,1]])
Y = np.array([[1,2,0],[0,-1,2]])
Z = np.array([[0,1],[2,3]])

dotresult = np.dot(Y,W)
squareresult = np.square(Z)
result6 = np.subtract(dotresult,squareresult)
print(result6) #False

[[ 5 -8]
 [ 0 -5]]
