<a href="https://colab.research.google.com/github/KhaledR/Linear-Algebra-58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Prelim Exam

##Question 1

In [20]:
import numpy as np

C = np.full((4,4),1)
print(C)
r = np.diag(C)
print(r)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[1 1 1 1]


##Question 2

In [19]:
r1 = np.square(C)
print(r1)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


##Question 3

In [4]:
A = np.array([2,7,4])
B = np.array([3,9,8])

result = np.cross(A,B)
print(result)


[20 -4 -3]
