<a href="https://colab.research.google.com/github/KhaledR/Linear-Algebra-58020/blob/main/Vector_Representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and its Operations 

In [ ]:
import numpy as np

#Create a 1x3 matrix

a = np.array([1,2,3])
print(a)


In [ ]:
#Create a 2x3 matrix

b = np.array([[1,2,3],[4,5,6]]) #This is an example of rectangular array
print(b)

In [ ]:
#Create a 3x3 matrix

c = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print(c)

In [ ]:
#Create a constant array with all values are 6

d = np.full((4,4),6) #This is an example of square matrix
print(d)

In [ ]:
#Create a diagonal matrix

e = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(e)
e = np.diagonal([[1,2,3],[4,5,6],[7,8,9]])
print(e)

In [ ]:
#Create an identity matrix 

f = np.eye(4)
print(f)

In [ ]:
#Create a zero matrix

g = np.zeros((4,5))
print(g)

In [ ]:
#Create an empty matrix

h = np.empty((0,5))
print(h)

In [25]:
#Addition of Matrices

i = np.array([[1,2,3],[4,5,6]])
j = np.zeros((2,3))
print(i+j)

[[1. 2. 3.]
 [4. 5. 6.]]


In [26]:
#Subtraction of Matrices

i = np.array([[1,2,3],[4,5,6]])
j = np.array([[-1,2,4],[7,4,2]])
print(i-j)


[[ 2  0 -1]
 [-3  1  4]]
